### ISSUE TITLE
Error:03000086:digital envelope routines::initialization error

### ISSUE THREAD

**Issue by bhumilsarvaiya** [supertokens/supertokens-auth-react#540]
Node version:  18.6

When starting the demo apps, the frontend server crashes with open ssl error:

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/bhumilsarvaiya/clones/supertokens/supertokens-auth-react/examples/with-emailpassword/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/bhumilsarvaiya/clones/supertokens/supertokens-auth-react/examples/with-emailpassword/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/bhumilsarvaiya/clones/supertokens/supertokens-auth-react/examples/with-emailpassword/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/bhumilsarvaiya/clones/supertokens/supertokens-auth-react/examples/with-emailpassword/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/bhumilsarvaiya/clones/supertokens/supertokens-auth-react/examples/with-emailpassword/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/bhumilsarvaiya/clones/supertokens/supertokens-auth-react/examples/with-emailpassword/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/bhumilsarvaiya/clones/supertokens/supertokens-auth-react/examples/with-emailpassword/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/bhumilsarvaiya/clones/supertokens/supertokens-auth-react/examples/with-emailpassword/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Comment by porcellus** [comment]
I've tested builds/startup in the auth-react, web-js, and website repos after the update with node 17 (when the above issue was introduced). They are working now.
