### ISSUE TITLE
Remix run question

### ISSUE THREAD

**Issue by kubeworkz** [supertokens/supertokens-auth-react#595]
I'm trying to run the following Supertokens code in Remix:

```
export const SuperTokensConfig = {
    appInfo: {
        appName: "SuperTokens Demo App",
        apiDomain: "http://localhost:3001",
        websiteDomain: "http://localhost:3000",
    },
    // recipeList contains all the modules that you want to
    // use from SuperTokens. See the full list here: https://supertokens.com/docs/guides
    recipeList: [
        ThirdPartyEmailPassword.init({
            signInAndUpFeature: {
                providers: [Github.init(), Google.init(), Apple.init()],
            },
        }),
        Session.init(),
    ],
};
```

It always throws the following error:
```
> remix-serve build


/home/osboxes/my-app/new-app/frontend/node_modules/supertokens-website/lib/build/utils/windowHandler/defaultImplementation.js:137
        throw Error(
              ^
Error: If you are using this package with server-side rendering, please make sure that you are checking if the window object is defined.
    at getWindowOrThrow (/home/osboxes/my-app/new-app/frontend/node_modules/supertokens-website/lib/build/utils/windowHandler/defaultImplementation.js:137:15)
    at Object.getDocument (/home/osboxes/my-app/new-app/frontend/node_modules/supertokens-website/lib/build/utils/windowHandler/defaultImplementation.js:288:16)
    at isIE (/home/osboxes/my-app/new-app/frontend/node_modules/supertokens-auth-react/lib/build/utils.js:430:84)
    at getShouldUseShadowDomBasedOnBrowser (/home/osboxes/my-app/new-app/frontend/node_modules/supertokens-auth-react/lib/build/recipe/recipeModule/utils.js:214:26)
    at normaliseRecipeModuleConfig (/home/osboxes/my-app/new-app/frontend/node_modules/supertokens-auth-react/lib/build/recipe/recipeModule/utils.js:191:20)
    at normaliseAuthRecipe (/home/osboxes/my-app/new-app/frontend/node_modules/supertokens-auth-react/lib/build/recipe/authRecipe/utils.js:20:52)
    at normaliseThirdPartyEmailPasswordConfig (/home/osboxes/my-app/new-app/frontend/node_modules/supertokens-auth-react/lib/build/recipe/thirdpartyemailpassword/utils.js:56:66)
    at new ThirdPartyEmailPassword (/home/osboxes/my-app/new-app/frontend/node_modules/supertokens-auth-react/lib/build/recipe/thirdpartyemailpassword/recipe.js:213:90)
    at /home/osboxes/my-app/new-app/frontend/node_modules/supertokens-auth-react/lib/build/recipe/thirdpartyemailpassword/recipe.js:371:48
    at /home/osboxes/my-app/new-app/frontend/node_modules/supertokens-auth-react/lib/build/superTokens.js:365:20
```
Adding a check for the window worked:
```
if (typeof window !== 'undefined') {
    SuperTokens.init(SuperTokensConfig);
}
```
... and I added useEffect => to:
```
    return (
        <SuperTokensWrapper>
            <div className="app">
                <Router>
                    <div className="fill">
                        <Routes>
                            {/* This shows the login UI on "/auth" route */}
                            {getSuperTokensRoutesForReactRouterDom(require("react-router-dom"))}

                            <Route
                                path="/"
                                element={
                                    /* This protects the "/" route so that it shows
                                  <Home /> only if the user is logged in.
                                  Else it redirects the user to "/auth" */
                                    <SessionAuth>
                                        <Home />
                                    </SessionAuth>
                                }
                            />
                        </Routes>
                    </div>
                </Router>
            </div>
        </SuperTokensWrapper>
  );
```
The errors went away but it also doesn't display the login screen. What am I missing? Cheers, Dave

**Comment by rishabhpoddar** [comment]
> ... and I added useEffect => to:

Where are you using useEffect?

> The errors went away but it also doesn't display the login screen. What am I missing?
`{getSuperTokensRoutesForReactRouterDom(require("react-router-dom"))}` should render the login screen on the `/auth` route. Do you see any console errors when visiting that route? If yes, what are they? If no, can you do a `console.log` in the main render function and see if that console log gets printed out?

**Comment by kubeworkz** [comment]
Here's my whole root.tsx file:
```
import { useState, useEffect } from "react";
import "./styles/app.css";
import SuperTokens, { SuperTokensWrapper, getSuperTokensRoutesForReactRouterDom } from "supertokens-auth-react";
import { SessionAuth } from "supertokens-auth-react/recipe/session";
import { Routes, BrowserRouter as Router, Route } from "react-router-dom";
import { Link } from "@remix-run/react";
import Home from "./Home";
import Footer from "./Footer";
import { SuperTokensConfig } from "./config";
import SessionExpiredPopup from "./SessionExpiredPopup";

if (typeof window !== 'undefined') {
    SuperTokens.init(SuperTokensConfig);
}

export default function App() {

    let [showSessionExpiredPopup, updateShowSessionExpiredPopup] = useState(false);

    return (
        <SuperTokensWrapper>
            <div className="App">
                <Router>
                    <div className="fill">
                        <Routes>
                                {getSuperTokensRoutesForReactRouterDom(require("react-router-dom"))}
                            <Route
                                path="/"
                                element={
                                    /* This protects the "/" route so that it shows
                                        <Home /> only if the user is logged in.
                                        Else it redirects the user to "/auth" */
                                    <SessionAuth
                                        onSessionExpired={() => {
                                            updateShowSessionExpiredPopup(true);
                                        }}>
                                        <Home />
                                        {showSessionExpiredPopup && <SessionExpiredPopup />}
                                    </SessionAuth>
                                }
                            />
                        </Routes>
                    </div>
                    <Footer />
                </Router>
            </div>
        </SuperTokensWrapper>
    );
}
```
When executing: 
```
{getSuperTokensRoutesForReactRouterDom(require("react-router-dom"))}
```
I get the following error:
```
Error: SuperTokens must be initialized before calling this method.
If you are trying to use this method doing server-side-rendering, please make sure you move this method inside a componentDidMount method or useEffect hook.
    at Function.SuperTokens.getInstanceOrThrow (/home/osboxes/my-app/new-app/frontend/node_modules/supertokens-auth-react/lib/build/superTokens.js:388:19)
    at Function.SuperTokens.getSuperTokensRoutesForReactRouterDom (/home/osboxes/my-app/new-app/frontend/node_modules/supertokens-auth-react/lib/build/superTokens.js:436:98)
    at SuperTokensAPIWrapper.getSuperTokensRoutesForReactRouterDom (/home/osboxes/my-app/new-app/frontend/node_modules/supertokens-auth-react/lib/build/index.js:206:38)
    at App (/home/osboxes/my-app/new-app/frontend/build/index.js:272:90)
    at Uc (/home/osboxes/my-app/new-app/frontend/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:70:44)
    at Xc (/home/osboxes/my-app/new-app/frontend/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:72:253)
    at Z (/home/osboxes/my-app/new-app/frontend/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:78:89)
    at Xc (/home/osboxes/my-app/new-app/frontend/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:76:231)
    at Z (/home/osboxes/my-app/new-app/frontend/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:78:89)
    at Xc (/home/osboxes/my-app/new-app/frontend/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:72:481)
```
I've attached the whole project. It's basically a Remix version of the recipe: `thirdpartyemailpassword` from supertokens-auth-react example => node backend / react frontend 
[new-app.tar.gz](https://github.com/supertokens/supertokens-auth-react/files/9718429/new-app.tar.gz)

**Comment by rishabhpoddar** [comment]
Ah right. I see. So you want to render `{getSuperTokensRoutesForReactRouterDom(require("react-router-dom"))}` only if it's on the client side. Try doing this:

```tsx
<Routes>
   {typeof window !== 'undefined' && getSuperTokensRoutesForReactRouterDom(require("react-router-dom"))}
   ...
</Routes>
```

**Comment by kubeworkz** [comment]
Thanks! I'll give it a shot.

**Comment by kubeworkz** [comment]
I get the same error:
```
Error: If you are using this package with server-side rendering, please make sure that you are checking if the window object is defined.
    at getWindowOrThrow (/home/osboxes/my-app/new-app/frontend/node_modules/supertokens-website/lib/build/utils/windowHandler/defaultImplementation.js:137:15)
    at Object.getDocument (/home/osboxes/my-app/new-app/frontend/node_modules/supertokens-website/lib/build/utils/windowHandler/defaultImplementation.js:288:16)
    at isIE (/home/osboxes/my-app/new-app/frontend/node_modules/supertokens-auth-react/lib/build/utils.js:430:84)
    at getShouldUseShadowDomBasedOnBrowser (/home/osboxes/my-app/new-app/frontend/node_modules/supertokens-auth-react/lib/build/recipe/recipeModule/utils.js:214:26)
    at normaliseRecipeModuleConfig (/home/osboxes/my-app/new-app/frontend/node_modules/supertokens-auth-react/lib/build/recipe/recipeModule/utils.js:191:20)
    at normaliseAuthRecipe (/home/osboxes/my-app/new-app/frontend/node_modules/supertokens-auth-react/lib/build/recipe/authRecipe/utils.js:20:52)
    at normaliseThirdPartyEmailPasswordConfig (/home/osboxes/my-app/new-app/frontend/node_modules/supertokens-auth-react/lib/build/recipe/thirdpartyemailpassword/utils.js:56:66)
    at new ThirdPartyEmailPassword (/home/osboxes/my-app/new-app/frontend/node_modules/supertokens-auth-react/lib/build/recipe/thirdpartyemailpassword/recipe.js:213:90)
    at /home/osboxes/my-app/new-app/frontend/node_modules/supertokens-auth-react/lib/build/recipe/thirdpartyemailpassword/recipe.js:371:48
    at /home/osboxes/my-app/new-app/frontend/node_modules/supertokens-auth-react/lib/build/superTokens.js:365:20
```
I've since found the problem is it can't do a `SuperTokens.init()` (under Remix).

**Comment by rishabhpoddar** [comment]
Hmm. That's really strange. It's basically throwing cause it can't find the window object - which should always be available if it's running on the frontend regardless of the framework being used.

Can you maybe step through the execution by adding a
```
debugger
```

statement right before the `SuperTokens.init(SuperTokensConfig);` line and seeing where it's getting executed?

**Comment by rishabhpoddar** [comment]
I tried with 
```
{typeof window !== 'undefined' && getSuperTokensRoutesForReactRouterDom(require("react-router-dom"))}
```

and the above error went away, instead, I got this:
```
ReferenceError: document is not defined
    at getUrlBasedHistory (/Users/rishabhpoddar/Desktop/new-app/frontend/node_modules/@remix-run/router/history.ts:543:18)
    at Object.createBrowserHistory (/Users/rishabhpoddar/Desktop/new-app/frontend/node_modules/@remix-run/router/history.ts:341:10)
    at BrowserRouter (/Users/rishabhpoddar/Desktop/new-app/frontend/node_modules/react-router-dom/index.tsx:246:26)
    at renderWithHooks (/Users/rishabhpoddar/Desktop/new-app/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:5724:16)
    at renderIndeterminateComponent (/Users/rishabhpoddar/Desktop/new-app/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:5797:15)
    at renderElement (/Users/rishabhpoddar/Desktop/new-app/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:6012:7)
    at renderNodeDestructiveImpl (/Users/rishabhpoddar/Desktop/new-app/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (/Users/rishabhpoddar/Desktop/new-app/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:6142:14)
    at renderNode (/Users/rishabhpoddar/Desktop/new-app/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:6325:12)
    at renderHostElement (/Users/rishabhpoddar/Desktop/new-app/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:5708:3)
    at renderElement (/Users/rishabhpoddar/Desktop/new-app/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:6018:5)
    at renderNodeDestructiveImpl (/Users/rishabhpoddar/Desktop/new-app/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:6170:11)
    at renderNodeDestructive (/Users/rishabhpoddar/Desktop/new-app/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:6142:14)
    at renderContextProvider (/Users/rishabhpoddar/Desktop/new-app/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:5986:3)
    at renderElement (/Users/rishabhpoddar/Desktop/new-app/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:6083:11)
    at renderNodeDestructiveImpl (/Users/rishabhpoddar/Desktop/new-app/frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:6170:11)
```

This error seems to come from react router dom library - I'm not familiar with remix, but is this library supposed to be used with Remix? I think they have their own router.

**Comment by rishabhpoddar** [comment]
I'm closing this issue since the SuperTokens related part is solved. However, please feel free to reopen if required.
